# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160621_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
