# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='catalogue.Product'),
        ),
    ]
